# Generated by Django 4.0.3 on 2022-03-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user1_delete_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
